name: "build-test"
on: [push]

jobs:
  test_something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/create-outputs@metronet-demo
      id: test
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: ${{ job.status }}
        output: |
          {"summary":${{ steps.test.outputs.summary }}}
